# Generated by Django 3.1.1 on 2020-10-25 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('username', models.CharField(default='def_user', max_length=20, primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='null', max_length=25)),
                ('lastname', models.CharField(default='null', max_length=30)),
                ('friends', models.ManyToManyField(blank=True, related_name='_contact_friends_+', to='geosmart_club_chat.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='geosmart_club_chat.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('messages', models.ManyToManyField(blank=True, to='geosmart_club_chat.Message')),
                ('participantes', models.ManyToManyField(related_name='chats', to='geosmart_club_chat.Contact')),
            ],
        ),
    ]
