# Generated by Django 3.1.1 on 2020-10-24 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosmart_club_chat', '0004_auto_20201017_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='geosmart_club_chat.contact'),
        ),
    ]
